version: '3.4'

services:
  onlineAuctionDb:
    image: mongo

  rabbitmq:
    image: rabbitmq:3-management

  onlineauctionSqlDb:
    image: mcr.microsoft.com/mssql/server

  onlineauction.product:
    image: ${DOCKER_REGISTRY-}onlineauctionproduct
    build:
      context: .
      dockerfile: Services/Product/OnlineAuction.Product/Dockerfile

  onlineauction.sourcing:
    image: ${DOCKER_REGISTRY-}onlineauctionsourcing
    build:
      context: .
      dockerfile: Services/Sourcing/OnlineAuction.Sourcing/Dockerfile


  onlineauction.order:
    image: ${DOCKER_REGISTRY-}onlineauctionorder
    build:
      context: .
      dockerfile: Services/Order/OnlineAuction.Order/Dockerfile


  onlineauction.apigateway:
    image: ${DOCKER_REGISTRY-}onlineauctionapigateway
    build:
      context: .
      dockerfile: ApiGateway/OnlineAuction.ApiGateway/Dockerfile

