version: '3.4'

services:
  onlineAuctionDb:
    image: mongo
  onlineauction.product:
    image: ${DOCKER_REGISTRY-}onlineauctionproduct
    build:
      context: .
      dockerfile: Services/Product/OnlineAuction.Product/Dockerfile

  onlineauction.sourcing:
    image: ${DOCKER_REGISTRY-}onlineauctionsourcing
    build:
      context: .
      dockerfile: Services/Sourcing/OnlineAuction.Sourcing/Dockerfile

